#!/bin/bash
# OCST Project - Script Help and Management
# Shows available scripts and their functions

echo "🚀 OCST Project - Available Scripts"
echo "===================================="
echo ""

echo "📊 EXPERIMENT SCRIPTS:"
echo "----------------------"
echo "  ./run_path_based_experiment.sh    - Run Path-Based Formulation experiments"
echo "  ./run_flow_based_experiment.sh    - Run Flow-Based Formulation experiments"
echo "  ./run_comparative_experiment.sh   - Run comparative analysis (both algorithms)"
echo "  ./run_analysis.sh                 - Run advanced statistical analysis"
echo ""

echo "🔧 BUILD SCRIPTS:"
echo "-----------------"
echo "  make all                          - Compile all algorithms"
echo "  make path_based                   - Compile Path-Based Formulation only"
echo "  make flow_based                    - Compile Flow-Based Formulation only"
echo "  make test_gurobi                   - Compile Gurobi test"
echo "  make run_test                      - Run Gurobi academic license test"
echo "  make check_gurobi                  - Verify Gurobi environment"
echo "  make clean                         - Clean build files"
echo "  make help                          - Show Makefile help"
echo ""

echo "📁 PROJECT STRUCTURE:"
echo "--------------------"
echo "  src/cpp/algorithms/"
echo "    ├── path_based_formulation/     - Path-Based MILP implementation"
echo "    └── flow_based_formulation/      - Flow-Based MILP implementation"
echo ""
echo "  experiments/"
echo "    ├── config/                     - Experiment configurations"
echo "    ├── scripts/                    - Experiment runner scripts"
echo "    └── results/                    - Generated CSV results"
echo ""

echo "🎯 QUICK START:"
echo "--------------"
echo "  1. Compile:     make all"
echo "  2. Test Gurobi: make run_test"
echo "  3. Run experiment: ./run_comparative_experiment.sh"
echo ""

echo "📋 USAGE EXAMPLES:"
echo "-----------------"
echo "  # Run comparative experiment with default settings"
echo "  ./run_comparative_experiment.sh"
echo ""
echo "  # Run with custom time limit (2 minutes)"
echo "  ./run_comparative_experiment.sh 120"
echo ""
echo "  # Run with custom time limit and heuristics"
echo "  ./run_comparative_experiment.sh 120 0.8"
echo ""
echo "  # Run individual algorithm experiments"
echo "  ./run_path_based_experiment.sh 60 0.5"
echo "  ./run_flow_based_experiment.sh 60 0.5"
echo ""
echo "  # Run advanced statistical analysis"
echo "  ./run_analysis.sh"
echo ""

echo "📊 RESULTS:"
echo "----------"
echo "  Results are saved in: experiments/results/"
echo "  Format: experimento_[algorithm]_[timestamp].csv"
echo "  Use CSV files for analysis and comparison"
echo ""

echo "ℹ️  For more information, check the README.md or individual script headers"
